export const CANDLE_CHART_CONFIGS = {
  PORTRAIT_DISPLAY_ASPECT_RATIO: 16 / 11, //
  REAL_ASPECT_RATIO: 16 / 9,
  LABEL_Y_WIDTH: 50,
  LABEL_X_HEIGHT: 30,
  TICK_WIDTH: 10, //
  TIME_HORIZONTAL_PADDING_TO_SCREEN_WIDTH_RATIO: 0.3,
  PRICE_UNITS_ON_SCREEN: 5,
  PRICE_PADDING_IN_PERCENTAGES: 10,
  TIME_UNITS_ON_DISPLAY: 5,
};
